import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClientProvider } from '@tanstack/react-query';
import { initSentry } from './lib/sentry';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import ErrorBoundary from './components/ErrorBoundary';
import { AuthProvider } from './contexts/AuthContext';
import { queryClient } from './lib/query-client';
import { clearLegacyPwaCaches } from './lib/pwa';
import './index.css';

// React Query DevTools - lazy load only in development
const ReactQueryDevtools = import.meta.env.DEV
  ? React.lazy(() => import('@tanstack/react-query-devtools').then((mod) => ({ default: mod.ReactQueryDevtools })))
  : null;

// Initialize Sentry error tracking (before React renders)
initSentry();

// Clean up legacy PWA caches from earlier builds (pre-vite-plugin-pwa SW).
clearLegacyPwaCaches().catch((err) => {
  console.warn('PWA legacy cache cleanup failed:', err);
});

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <App />
        </AuthProvider>
        {/* React Query DevTools - only in development */}
        {ReactQueryDevtools && (
          <React.Suspense fallback={null}>
            <ReactQueryDevtools initialIsOpen={false} />
          </React.Suspense>
        )}
      </QueryClientProvider>
    </ErrorBoundary>
  </React.StrictMode>
);

// Register the SW generated by vite-plugin-pwa (autoUpdate).
if (import.meta.env.PROD) {
  registerSW({
    immediate: true,
    onRegisterError(error) {
      console.error('PWA service worker registration failed:', error);
    }
  });
}

// Initialize Web Vitals tracking
import { initWebVitals } from './lib/monitoring/webVitals';
initWebVitals();
