import React from 'react';
import ReactDOM from 'react-dom/client';
import { initSentry } from './lib/sentry';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import ErrorBoundary from './components/ErrorBoundary';
import { AuthProvider } from './contexts/AuthContext';
import { ThemeProvider } from './contexts/ThemeContext';
import { clearLegacyPwaCaches } from './lib/pwa';
import './index.css';

// Initialize Sentry error tracking (before React renders)
initSentry();

// Clean up legacy PWA caches from earlier builds (pre-vite-plugin-pwa SW).
clearLegacyPwaCaches().catch((err) => {
  console.warn('PWA legacy cache cleanup failed:', err);
});

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <ErrorBoundary>
      <ThemeProvider>
        <AuthProvider>
          <App />
        </AuthProvider>
      </ThemeProvider>
    </ErrorBoundary>
  </React.StrictMode>
);

// Register the SW generated by vite-plugin-pwa (autoUpdate).
if (import.meta.env.PROD) {
  registerSW({
    immediate: true,
    onRegisterError(error) {
      console.error('PWA service worker registration failed:', error);
    }
  });
}

// Report Core Web Vitals in production
if (import.meta.env.PROD) {
  import('web-vitals').then(({ onCLS, onFCP, onLCP, onTTFB }) => {
    const sendToAnalytics = (metric: { name: string; value: number; id: string }) => {
      // Log to console for debugging (replace with analytics service)
      console.log(`[Web Vital] ${metric.name}: ${Math.round(metric.value)}`, metric.id);

      // TODO: Send to Cloudflare Analytics or similar
      // Example: navigator.sendBeacon('/api/vitals', JSON.stringify(metric));
    };

    onCLS(sendToAnalytics);
    onFCP(sendToAnalytics);
    onLCP(sendToAnalytics);
    onTTFB(sendToAnalytics);
  });
}
