#!/bin/bash
# RLS Security Testing Script
# Tests Row Level Security policies with different roles

set -e

echo "=== RLS Security Testing Guide ==="
echo ""
echo "This script provides guidance for testing Row Level Security policies"
echo "with different user roles to verify security."
echo ""

# Check if supabase is linked
if ! supabase status > /dev/null 2>&1; then
    echo "⚠️  WARNING: Supabase not linked"
    echo "Please run: supabase link --project-ref YOUR_PROJECT_REF"
    exit 1
fi

echo "✅ Supabase project linked"
echo ""

echo "=== User Roles to Test ==="
echo ""
echo "1. PLATFORM_ADMIN (Super Admin)"
echo "   - Should access all institutions"
echo "   - Should access all data across institutions"
echo ""
echo "2. INSTITUTION_ADMIN (Branch Manager)"
echo "   - Should access only their institution"
echo "   - Should manage staff and settings"
echo ""
echo "3. INSTITUTION_STAFF (Regular Staff)"
echo "   - Should access only their institution"
echo "   - Should view and create data"
echo "   - Should NOT update/delete sensitive data"
echo ""
echo "4. INSTITUTION_TREASURER"
echo "   - Should access only their institution"
echo "   - Should view financial data"
echo ""
echo "5. INSTITUTION_AUDITOR"
echo "   - Should access only their institution"
echo "   - Should view audit logs"
echo ""
echo "6. Unauthenticated (Anonymous)"
echo "   - Should NOT access any data"
echo ""

echo "=== Test Scenarios ==="
echo ""
echo "1. Cross-Institution Access Prevention"
echo "   - User from Institution A should NOT see Institution B data"
echo "   - Test with: groups, members, transactions, profiles"
echo ""
echo "2. Role-Based Permissions"
echo "   - Staff can view but not delete"
echo "   - Admins can update/delete"
echo "   - Platform Admin can access all"
echo ""
echo "3. Table-Level Security"
echo "   - Test all tables with RLS enabled"
echo "   - Verify policies are working"
echo ""
echo "4. RPC Function Security"
echo "   - Test RPC functions respect RLS"
echo "   - Verify role checks in functions"
echo ""
echo "5. Edge Function Security"
echo "   - Test Edge Functions check permissions"
echo "   - Verify unauthorized access is blocked"
echo ""

echo "=== Manual Testing Steps ==="
echo ""
echo "1. Create test users with different roles:"
echo "   - See: scripts/create-test-users.sql"
echo ""
echo "2. Test with Supabase SQL Editor:"
echo "   - Run: scripts/test-rls-policies.sql"
echo "   - Replace placeholders with actual user IDs"
echo ""
echo "3. Test with application:"
echo "   - Log in as different users"
echo "   - Verify they only see their institution's data"
echo "   - Test CRUD operations"
echo ""
echo "4. Test cross-institution access:"
echo "   - Try to access another institution's data"
echo "   - Should fail or return empty"
echo ""

echo "=== Expected Behavior ==="
echo ""
echo "✅ PLATFORM_ADMIN should:"
echo "   - See all institutions"
echo "   - Access all data"
echo "   - Manage all settings"
echo ""
echo "✅ INSTITUTION_ADMIN should:"
echo "   - See only their institution"
echo "   - Manage staff in their institution"
echo "   - Update settings for their institution"
echo ""
echo "✅ INSTITUTION_STAFF should:"
echo "   - See only their institution"
echo "   - View and create data"
echo "   - NOT delete sensitive data"
echo ""
echo "❌ All roles should NOT:"
echo "   - Access other institutions' data"
echo "   - Bypass RLS policies"
echo "   - Access data without authentication"
echo ""

echo "=== Security Verification Checklist ==="
echo ""
echo "- [ ] Platform Admin can access all institutions"
echo "- [ ] Institution Admin can only access their institution"
echo "- [ ] Staff can only access their institution"
echo "- [ ] Cross-institution access is blocked"
echo "- [ ] Unauthenticated access is blocked"
echo "- [ ] RPC functions respect RLS"
echo "- [ ] Edge Functions check permissions"
echo "- [ ] Audit logs are protected"
echo "- [ ] Settings are institution-scoped"
echo "- [ ] Profiles are properly protected"
echo ""

echo "=== Troubleshooting ==="
echo ""
echo "If RLS is not working:"
echo "1. Verify RLS is enabled on tables"
echo "2. Check policies are created correctly"
echo "3. Verify helper functions exist"
echo "4. Check user roles in profiles table"
echo "5. Verify institution_id is set correctly"
echo ""

echo "=== Verification Complete ==="
echo ""
echo "Next steps:"
echo "1. Create test users (see: scripts/create-test-users.sql)"
echo "2. Run RLS tests (see: scripts/test-rls-policies.sql)"
echo "3. Test in application with different users"
echo "4. Document results in: docs/security/RLS_TEST_RESULTS.md"
