#!/bin/bash
# Report Generation Performance Testing Script
# Tests report generation with large date ranges and datasets

set -e

echo "=== Report Generation Performance Testing ==="
echo ""
echo "This script will guide you through testing report generation"
echo "performance with large date ranges and datasets."
echo ""

# Check if supabase is linked
if ! supabase status > /dev/null 2>&1; then
    echo "⚠️  WARNING: Supabase not linked"
    echo "Please run: supabase link --project-ref YOUR_PROJECT_REF"
    exit 1
fi

echo "✅ Supabase project linked"
echo ""

echo "=== Test Scenarios ==="
echo ""
echo "1. Weekly Report (7 days)"
echo "   - Expected: < 3 seconds"
echo "   - Test with: 1000+ transactions"
echo ""
echo "2. Monthly Report (30 days)"
echo "   - Expected: < 5 seconds"
echo "   - Test with: 5000+ transactions"
echo ""
echo "3. Quarterly Report (90 days)"
echo "   - Expected: < 10 seconds"
echo "   - Test with: 15000+ transactions"
echo ""
echo "4. Yearly Report (365 days)"
echo "   - Expected: < 15 seconds"
echo "   - Test with: 50000+ transactions"
echo ""
echo "5. Overall Report (All time)"
echo "   - Expected: < 20 seconds"
echo "   - Test with: 100000+ transactions"
echo ""

echo "=== Manual Testing Steps ==="
echo ""
echo "1. Ensure you have test data:"
echo "   - Run: supabase/seed/014_large_dataset_performance_test.sql"
echo "   - Or use existing data with large date ranges"
echo ""
echo "2. Open the application in browser"
echo ""
echo "3. Navigate to Reports page"
echo ""
echo "4. Test each scenario:"
echo "   a. Select a group or institution"
echo "   b. Set date range (start with weekly, then monthly, etc.)"
echo "   c. Click 'Generate Report'"
echo "   d. Measure time from click to report display"
echo "   e. Check browser DevTools → Network tab for query times"
echo ""
echo "5. Monitor performance:"
echo "   - Open DevTools → Performance tab"
echo "   - Start recording"
echo "   - Generate report"
echo "   - Stop recording"
echo "   - Check for long tasks (> 50ms)"
echo ""
echo "6. Check database query performance:"
echo "   - Run EXPLAIN ANALYZE on report queries"
echo "   - See: scripts/report-query-benchmarks.sql"
echo ""

echo "=== Performance Benchmarks ==="
echo ""
echo "| Report Type | Date Range | Target Time | Max Acceptable |"
echo "|-------------|------------|-------------|----------------|"
echo "| Weekly      | 7 days     | < 3s        | < 5s           |"
echo "| Monthly     | 30 days    | < 5s        | < 10s          |"
echo "| Quarterly   | 90 days    | < 10s       | < 20s          |"
echo "| Yearly      | 365 days   | < 15s       | < 30s          |"
echo "| Overall     | All time   | < 20s       | < 40s          |"
echo ""

echo "=== Expected Behavior ==="
echo ""
echo "✅ Report generation should:"
echo "   - Show loading indicator during generation"
echo "   - Complete within target times"
echo "   - Display accurate data"
echo "   - Handle errors gracefully"
echo "   - Support CSV export"
echo ""
echo "❌ Report generation should NOT:"
echo "   - Timeout (> 60 seconds)"
echo "   - Freeze the UI"
echo "   - Show incorrect data"
echo "   - Crash the browser"
echo ""

echo "=== Troubleshooting ==="
echo ""
echo "If reports are slow:"
echo "1. Check database indexes (see: docs/database/INDEX_PERFORMANCE_VERIFICATION.md)"
echo "2. Verify RPC functions are optimized"
echo "3. Check for N+1 queries"
echo "4. Verify date range filters are using indexes"
echo "5. Check network latency"
echo ""

echo "=== Verification Complete ==="
echo ""
echo "Next steps:"
echo "1. Run manual tests as described above"
echo "2. Document results in: docs/performance/REPORT_GENERATION_TEST_RESULTS.md"
echo "3. Run query benchmarks: scripts/report-query-benchmarks.sql"
echo "4. Optimize slow queries if needed"
