/// <reference types="./types/global" />
import React from 'react';
import ReactDOM from 'react-dom/client';
import { initSentry } from './lib/sentry';
import { registerSW } from 'virtual:pwa-register';

import App from './App';
import { GlobalErrorBoundary } from './components/GlobalErrorBoundary';
import { AuthProvider } from './contexts/AuthContext';
import { ThemeProvider } from './contexts/ThemeContext';
import { clearLegacyPwaCaches } from './lib/pwa';
import './index.css';

// Initialize Sentry error tracking (before React renders)
initSentry();

// Clean up legacy PWA caches from earlier builds (pre-vite-plugin-pwa SW).
clearLegacyPwaCaches().catch((err) => {
  console.warn('PWA legacy cache cleanup failed:', err);
});

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <GlobalErrorBoundary>
      <ThemeProvider>
        <AuthProvider>
          <App />
        </AuthProvider>
      </ThemeProvider>
    </GlobalErrorBoundary>
  </React.StrictMode>
);

// Register the SW generated by vite-plugin-pwa (autoUpdate).
if (import.meta.env.PROD) {
  registerSW({
    immediate: true,
    onRegisterError(error) {
      console.error('PWA service worker registration failed:', error);
    }
  });
}

// Report Core Web Vitals in production
if (import.meta.env.PROD) {
  import('./lib/performance/webVitals').then(({ initWebVitals }) => {
    initWebVitals();
  });
}
